# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: main
'on': [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --verbose --all-files
  release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [commitlint, pre-commit]
    runs-on: ubuntu-latest
    container: myii/ssf-semantic-release:15.14
    steps:
      - uses: actions/checkout@v2
      - run: semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
