# -*- coding: utf-8 -*-
# vim: ft=yaml
---
name: release
'on': workflow_dispatch

jobs:
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    container: myii/ssf-semantic-release:15.14
    steps:
      - uses: actions/checkout@v2
      - run: |
          /root/go/bin/maintainer contributor
          semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAINTAINER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
